/*
**The MIT License (MIT)
**Copyright (c) <2014> <CIn-UFPE>
** 
**Permission is hereby granted, free of charge, to any person obtaining a copy
**of this software and associated documentation files (the "Software"), to deal
**in the Software without restriction, including without limitation the rights
**to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
**copies of the Software, and to permit persons to whom the Software is
**furnished to do so, subject to the following conditions:
** 
**The above copyright notice and this permission notice shall be included in
**all copies or substantial portions of the Software.
** 
**THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
**IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
**FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
**AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
**LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
**OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
**THE SOFTWARE.
*/


package org.lanca.gui.components;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.caboclo.activities.Activity;
import org.caboclo.service.ConsoleOutput;


public class ConsolePanel extends javax.swing.JPanel {

    private final Set<String> activitiesId;
    
    /**
     * Creates new form ConsolePanel
     */
    public ConsolePanel() {
        initComponents();   
        
        activitiesId = new HashSet<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Console output"));
        setLayout(new java.awt.BorderLayout());
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    
    public void addActivity(Activity act){
        
        activitiesId.add(act.getId());        
        
        ConsoleTextArea consoleTxt = new ConsoleTextArea(act);
        
        JScrollPane scrl = new JScrollPane(consoleTxt, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        int i = jTabbedPane1.getTabCount();
        
        jTabbedPane1.add("Output", scrl);
        
        jTabbedPane1.setTabComponentAt(i, new ButtonTabComponent(jTabbedPane1));
        
        
    }
    
    public boolean hasActivity(Activity act){
        return activitiesId.contains(act.getId());
    }
    
    private static class ConsoleTextArea extends JTextArea 
    {
        public ConsoleTextArea(Activity activity) {
            super();
            
            activity.setConsole(new ConsoleOutput() {
                @Override
                public void printOutput(String str) {            
                    append(str + "\n");
                }
            });            
        }                        
    }
}
